### ISSUE TITLE
Sensibilizar y promover el uso de Test Pilot en los miembros de la comunidad antes del 31 de enero 2017.

### ISSUE THREAD

**Issue by siclemx** [mozillamexico/planes#1]
## Objetivo a alcanzar:
Sensibilizar y promover el uso de Test Pilot en los miembros de la comunidad antes del 31 de enero 2017. 

## Documentos relacionados y enlaces

* [Instalación Test Pilot](https://testpilot.firefox.com/?utm_source=activity.mozilla.community%26utm_medium%3Dreferral%26utm_campaign%3Dmoz-community-2016)

## Roles

* **R**esponsable: @odinm 

* **A**ccountable @odinm  
* **S**upporter (apoyo): Dani y Ximena (xaxynapalm) @bosicle
* **C**onsulted (consultado): @lasr21  
* **I**nformed (informado): @deimidis 

## Lista de items:
- [ ] Se realizaran los talleres de manera interna por medio de  Jitsy Meet (R: @username)

## Issues relacionados

* [Referencia a issues que contienen a este o anteriores](/thelink)

**Comment by deimidis** [comment]
Hola @BoSicle quizás podrías agregar más pasos en la «lista de items» que te permita hacer un mejor seguimiento del estado del proyecto.

Por ejemplo alguno que haga referencia a la preparación del material, o los diferentes encuentros que se realizarán, etc.

Por otro lado, agregar en el objetivo de qué forma vas a medir el éxito del proceso, ¿cuántas personas deberían hacer qué para logra haber «sensibilizado» a la comunidad?

**Comment by mautematico** [comment]
Cuéntame entre los que ya lo tienen instalado 👍 
![screenshot_20161201_100201](https://cloud.githubusercontent.com/assets/1238928/20801052/41ad98a8-b7ad-11e6-9cf5-a5c66cb6caf5.png)

Me quedo con esos tres tests por ahora, y me mantengo al tanto de lo que vaya ocurriendo con esta tarea.

**Comment by robertonunezc** [comment]
Como vamos a medir esta tarea...Saber cuantos ya lo instalaron?

**Comment by Heeled-Jim** [comment]
Ya instalé Test Pilot en todos lados :)

**Comment by siclemx** [comment]
Hola, el responsable de Test Pilot es @odinm :) yo estoy de supporter jeje

**Comment by deimidis** [comment]
Buenas a todos, @odinm ¿puedes avanzar con esto? Si no podemos ver quién otro puede ayudar

**Comment by odinm** [comment]
Hola @deimidis se ha invitado a la comunidad de Mozilla México a instalar Test Pilot sin tener mucha respuesta al respecto, se seguirá insistiendo en la instalación, se buscará la ayuda de los que asistieron al encuentro, esperando tener una mayor respuesta de este grupo. 

No puedo modificar este plan para ajustarlo y poner más items, por lo tanto los pongo aquí.  

Items:
- Se realizaran los talleres de manera interna por medio de Jitsy Meet (R: @BoSicle ), ya realizo el primero pero se tuvo que reagendar, no se si por falta de asistentes, se programará ¿ya tienes fecha @BoSicle ? 

- Se realizará una campaña en redes sociales iniciando el año, se esta trabajando en el material el cual se usará el video localizado de Test Pilot. este se dividirá por cada elemento que se describe y para poder promocionarlo por separado, en caso de que no sea posible se estará promocionando sin el video cada una de las actividades, en esto estamos trabajando Dani y yo.

-Se invitará nuevamente a la comunidad de Mozilla México y a los que asistieron al encuentro (esperando sean los que nos puedan apoyar más) a que lo instalen y manden captura de pantalla, una vez que  las tengamos, los usaremos de referencia para promover el uso en las redes sociales.

Impacto deseado: 33 personas, que es la mitad del número de integrantes en los que están en el grupo de MozMX en Telegram. 

Impacto esperado: 20 personas, un número no máximo de los que fueron al encuentro, reiterando un mayor compromiso en ayudar por parte de ellos para que logremos alcanzar el objetivo. 

Saludos,
