### ISSUE TITLE
Proponer un plan de participación con ejemplos prácticos de RUST en web

### ISSUE THREAD

**Issue by Heeled-Jim** [mozillamexico/planes#10]
## Objetivo a alcanzar: 
Proponer un plan de participación para nuevos usuarios con ejemplos prácticos de RUST en web para 23 / Ene / 2017

## Documentos relacionados:
Wiki oficial del equipo RUST de Mozilla México: https://wiki.mozilla.org/Mexico/Rust

* Enlaces:
Mozilla Activate - RUST: https://activate.mozilla.community/es/rust-hack/
Documentación oficial de RUST: https://doc.rust-lang.org/stable/book/
Proyecto Servo en GitHub: https://github.com/servo/servo
Juega con RUST: https://play.rust-lang.org/
RUST by example: http://rustbyexample.com/
Framework Web para Rust: https://rocket.rs/
Meetup de la comunidad Rust MX: https://www.meetup.com/Rust-MX/
Introducción a RUST por Mario García: http://mariog.xyz/rust-slides/#/

## Roles:
* **R**esponsables: Sebastián Magrí @sebasmagri y Rodrigo Moreno @rodmoreno
* **A**ccountable (quien rinde cuentas): Abiel Parra @Heeled-Jim
* **S**upporter (apoyo): Mario Martínez @aio00
                                      Edgardo Ríos @edgardorios 
                                      Elesban Landero @tuxlan 
                                      David Salgado @KuronekoKat
                                      Yuli Reyna @yulireyji
                                      Abiel Parra @Heeled-Jim
* **C**onsulted (consultado): Alex Fuser @alexfuser
* **I**nformed (informado): Guillermo @deimidis
                                           Rubén @nukeador  
                                           Comunidad @mozillamexico

## Lista de items:
- [ ] Proponer el primer borrador del plan de participación el lunes 16 / Ene / 2017 (R: @sebasmagri, @rodmoreno, @Heeled-Jim)
- [ ] Ayudar con ajustes al contenido del primer borrador del plan de participación el miércoles 18 / Ene / 2017 (R: @aio00, @tuxlan, @KuronekoKat, @alexfuser)
- [ ] Publicar el plan de participación en la Wiki para el lunes 23 / Ene / 2017 (R: @edgardorios)
- [x] Proponer los primeros tutoriales con ejemplos prácticos de RUST en web con Iron/Rocket/NodeJs el miércoles 25 / Ene / 2017 (R: @sebasmagri, @rodmoreno)

## Issues relacionados:

* https://github.com/mozillamexico/planes/issues/3
* https://github.com/mozillamexico/planes/issues/8
* https://github.com/mozillamexico/planes/issues/9
* https://github.com/mozillamexico/planes/issues/11
* https://github.com/mozillamexico/planes/issues/12

**Comment by deimidis** [comment]
Hola, vi que hicieron el evento el otro día, ¿qué tal salió? ¿lograron cumplir con esto antes del evento?

**Comment by Heeled-Jim** [comment]
Hola @deimidis , el evento salió muy bien, estamos preparando el siguiente y actividades derivadas del primero como un posible boletín mensual, te mantendré informado al respecto. Esta actividad en particular tendrá una nueva fecha de entrega...

**Comment by sebasmagri** [comment]
Hola, existe alguna base que deba considerar para realizar la propuesta del Plan de participación?

Saludos cordiales,

**Comment by Heeled-Jim** [comment]
Hola @sebasmagri no tenemos un formato específico para las propuestas de trabajo, te invito a que propongas una y nos la compartas porfavor, si necesitas ayuda aqui estamos en contacto... saludos

**Comment by Heeled-Jim** [comment]
Hola @sebasmagri, @aio00 y @rodmoreno, después de la charla que tuvimos en el evento pasado, este issue me parece más apropiado moverlo para el nuevo repo de la Comunidad RustMX, ¿que opinan?

**Comment by sebasmagri** [comment]
@Heeled-Jim +1 por mi parte.

**Comment by tuxlan** [comment]
@Heeled-Jim de acuerdo.

**Comment by Heeled-Jim** [comment]
Ok, procedo a cerrar este issue y tomarlo como referencia...
