### ISSUE TITLE
Generar 4 convenios de colaboración con personas/organizaciones interesadas en proyectos basados en RUST

### ISSUE THREAD

**Issue by Heeled-Jim** [mozillamexico/planes#12]
## Objetivo a alcanzar: 
Generar 4 convenios de colaboración con las personas/organizaciones interesadas en trabajar con nuevos proyectos basados en RUST para el 23 / Ene / 2017

## Documentos relacionados:
Wiki oficial del equipo RUST de Mozilla México: https://wiki.mozilla.org/Mexico/Rust

* Enlaces:
Mozilla Activate - RUST: https://activate.mozilla.community/es/rust-hack/
Documentación oficial de RUST: https://doc.rust-lang.org/stable/book/
Proyecto Servo en GitHub: https://github.com/servo/servo
Juega con RUST: https://play.rust-lang.org/
RUST by example: http://rustbyexample.com/
Framework Web para Rust: https://rocket.rs/
Meetup de la comunidad Rust MX: https://www.meetup.com/Rust-MX/
Introducción a RUST por Mario García: http://mariog.xyz/rust-slides/#/

## Roles:
* **R**esponsable: Elesban Landero @tuxlan
* **A**ccountable (quien rinde cuentas): Abiel Parra @Heeled-Jim
* **S**upporter (apoyo): Yuli Reyna @yulireyji
                                      Edgardo Ríos @edgardorios 
                                      Alex Fuser @alexfuser
                                      David Salgado @KuronekoKat
                                      Rodrigo Moreno @rodmoreno
                                      Uriel Jurado @BoSicle 
                                      Abiel Parra @Heeled-Jim
* **C**onsulted (consultado): Mario Martínez @aio00, Jorge Díaz @jdiazmx 
* **I**nformed (informado): Guillermo @deimidis
                                           Rubén @nukeador  
                                           Comunidad @mozillamexico

## Lista de items:
- [ ] Proponer el primer plan de acción para la creación de proyectos basados en Rust para el viernes 13 / Ene / 2017 (R: @tuxlan, @Heeled-Jim)
- [ ] Generar un boletín de difusión en conjunto con la comunidad Rust CDMX con los proyectos activos y organizaciones que estén trabajando con RUST para el lunes 16 / Ene / 2017 (R: @tuxlan)
- [ ] Generar los primeros 4 convenios de colaboración (uno relacionado con Mozilla Lab Science) para proyectos basados en RUST para el viernes 20 / Ene / 2017 (R: @tuxlan, @BoSicle y @Heeled-Jim)
- [ ] Añadir a la wiki una sección con los proyectos activos y un histórico para el lunes 23 / Ene / 2017 (R: @edgardorios)

## Issues relacionados:

* https://github.com/mozillamexico/planes/issues/3
* https://github.com/mozillamexico/planes/issues/8
* https://github.com/mozillamexico/planes/issues/9
* https://github.com/mozillamexico/planes/issues/10
* https://github.com/mozillamexico/planes/issues/11

**Comment by deimidis** [comment]
Hola @Heeled-Jim todas las fechas de los items son similares, ¿no convendría poner todo en diferentes días? Así de paso sabemos el orden en el que deben ser terminados.

**Comment by Heeled-Jim** [comment]
Muchas gracias por el feedback @deimidis en estos días haremos los ajustes...

**Comment by Heeled-Jim** [comment]
Hola @tuxlan y @aio00, después de la charla que tuvimos en el meetup pasado, este issue parece más apropiado moverlo para el nuevo repo de la Comunidad RustMX, @sebasmagri propuso manejar un boletín de información estilo "This week in Rust" (https://this-week-in-rust.org/) qué más bien sería algo como "Este mes en Rust MX" :) ¿que opinan?

Para los convenios @BoSicle y un servidor estamos empezando a trabajar con el Study Group y podemos generar uno de investigación sin problema...

**Comment by Heeled-Jim** [comment]
Los issues pendientes relacionados con Rust quedarán cerrados para dar libertad a una nueva planeación con el nuevo responsable :)
Saludos
