### ISSUE TITLE
Webcompat a la mexicana

### ISSUE THREAD

**Issue by alex-mayorga** [mozillamexico/planes#2]
## Objetivo a alcanzar:
Lograr 30 instalaciones de Webcompat Reporter en México antes del 5 de Enero de 2017.
Lograr 30 reportes de problemas de Webcompat de México antes del 5 de Enero de 2017.

## Documentos relacionados y enlaces

* https://activate.mozilla.community/webcompat-sprint/
* https://addons.mozilla.org/es-MX/firefox/addon/webcompatcom-reporter/
* https://webcompat.com/

## Roles

* **R**esponsable: *(Obligatorio) La persona que liderará esta tarea (asigna el issue a esta persona)* @alex-mayorga
* **A**ccountable (quien rinde cuentas): *(Obligatorio) La persona que es responsable de todo el tópico, usualmente el líder del Tópico más grande)* @alex-mayorga
* **S**upporter (apoyo): *cualquier persona que ayude en esta tarea para que se complete* @alexfuser, @danysriot, @leonshion, @h3dx0, @kuronekokat, @jdiazmx, @lasr21
* **C**onsulted (consultado): *Persona que debe ser consultada para feedback o revisar la tarea, usualmente el Accountable* @alex-mayorga
* **I**nformed (informado): *Personas que deben ser avisadas del progreso de la tarea* @deimidis

## Lista de items:
- [ ] Localizar Webcompat a es-MX (R: @alex-mayorga)
- [ ] Publicar 3 posts en medios de difusión sobre WebCompat (R: @alexfuser)
- [ ] Publicar 2 posts en redes sociales sobre WebCompat (R: @danysriot)
- [ ] Lograr que "Todos" los miembros de Mozilla México instalen https://addons.mozilla.org/es/firefox/addon/webcompatcom-reporter/ (R: @alex-mayorga)
- [ ] Realizar una "Webcompat Posada" en Puebla (R: @leonshion)
- [ ] Realizar una "Webcompat Posada" en Coyoacán (R: @danysriot)
- [ ] Realizar una "Webcompat Posada" en Narvarte (R: @alexfuser)
- [ ] Realizar una "Webcompat Posada" en Queretaro (R: @h3dx0)
- [ ] Realizar una video tutorial de Webcompat (R: @kuronekokat)
- [ ] Contactar a las comunidades de desarrollo web y mostrarles Webcompat (R: @jdiazmx)
- [ ] Rosca de reyes de celebración (R: @lasr21)

## Issues relacionados

* [Referencia a issues que contienen a este o anteriores](/thelink)

**Comment by lasr21** [comment]
@alex-mayorga duda, ahora que puse un issue me lo rebotaron por que no era un problema de webcompat sino que el developer de la página le faltaba ver mas css. me podrias explicar cual es la diferencia y que exactamente es un problema de webcompat?

**Comment by mautematico** [comment]
¡Hola!
Me gustaría ayudar con la l10n de webcompat. Dónde nos vemos,
@alex_mayorga?

**Comment by deimidis** [comment]
Hola @alex-mayorga sería bueno que pudieran terminar con las parte del modelo RASCI de este issue.

**Comment by alex-mayorga** [comment]
@lasr21 ¿Tienes el enlace a tu bug? En teoría un bug de compatibilidad, es algo que funciona bien en el navegador A, pero no en B, C o D. Si el CSS se ve chafo en todos entonces no es un bug.

@mautematico Pregunté en https://vector.im/develop/#/room/#mozilla_#webcompat:matrix.org/$1480109695457146pzfuT:matrix.org Al parecer el temor del equipo es que les empiecen a llegar reportes en otros idiomas que no sean inglés.

@deimidis Ya edité esa sección, pero mo me termina de gustar que haya tantos @alex-mayorga ahí. ¿Puedes revisar, por favor?

**Comment by lasr21** [comment]
@alex-mayorga me queda muy claro ahora, el bug era https://github.com/webcompat/web-bugs/issues/3768 creo que una pequeña guia de 

Si no sirve en Firefox, prueba en navegador B,C,D si no tampoco en esos navegadores es un problema de que el programador le hace falta pulir el sitio, si se ve bien en otro naveagdor tenemos un problema de compatiblidad.

**Comment by deimidis** [comment]
Hola @alex-mayorga creo que está bien, aunque el Responsable y el accountable podrían ser diferentes.

¿Han podido avanzar en esto?

**Comment by alex-mayorga** [comment]
@leonshion, @danysriot, @alexfuser, @h3dx0, @kuronekokat, @jdiazmx 

¿Pueden por favor confirmar si sus actividades ya están completas?

**Comment by robertonunezc** [comment]
La posada la tengo programada para inicios de enero cuando lleguen todos mis colegas...

**Comment by leonshion** [comment]
Yo tengo programada la posada de igual forma por enero finales. Porque ando armando otro evento y en diciembre tuve un problema de salud. De todas formas los mantengo al tanto por este medio. Feliz año a todos.
