### ISSUE TITLE
Difundir y promover por medio de las redes sociales el uso de Test Pilot por medio de imagenes, videos.

### ISSUE THREAD

**Issue by siclemx** [mozillamexico/planes#4]
## Objetivo a alcanzar:
Difundir y promover por medio de las redes sociales el uso de Test Pilot por medio de imagenes,  videos.

## Documentos relacionados y enlaces

* [Enlaces aquí](/thelink)

## Roles

* **R**esponsable: *(Obligatorio) La persona que liderará esta tarea (asigna el issue a esta persona)*
* **A**ccountable (quien rinde cuentas): *(Obligatorio) La persona que es responsable de todo el tópico, usualmente el líder del Tópico más grande)*
* **S**upporter (apoyo): *cualquier persona que ayude en esta tarea para que se complete*
* **C**onsulted (consultado): *Persona que debe ser consultada para feedback o revisar la tarea, usualmente el Accountable*
* **I**nformed (informado): *Personas que deben ser avisadas del progreso de la tarea*

## Lista de items:
- [ ] Hecho particular que debe suceder (R: @username)
- [ ] Hecho particular que debe suceder (R: @username)
- [ ] Hecho particular que debe suceder (R: @username)
- [ ] Hecho particular que debe suceder (R: @username)

## Issues relacionados

* [Referencia a issues que contienen a este o anteriores](/thelink)

**Comment by deimidis** [comment]
Hola @BoSicle ¿van a trabajar en este? Si no podemos cerrarlo para que no distraiga

**Comment by siclemx** [comment]
Cierro.
