### ISSUE TITLE
Trabajar con WebVR apoyados en alianzas con comunidades existentes en México 

### ISSUE THREAD

**Issue by LeZelt** [mozillamexico/planes#5]
## Objetivo a alcanzar:
Trabajar con WebVR apoyados en alianzas con comunidades existentes en México y de esta manera tener un equipo activo de 8 personas comprometidas con los objetivos.

## Documentos relacionados y enlaces

* [Sitio Aframe](https://aframe.io/)
* [Sitio Guri](https://gurivr.com/)
* [Grupo de Telegram](https://telegram.me/joinchat/ACYsq0BwntgTvQM3Um7miw)

## Roles

* **R**esponsable: *(Obligatorio) La persona que liderará esta tarea (asigna el issue a esta persona)*
* **A**ccountable (quien rinde cuentas): *(Obligatorio) La persona que es responsable de todo el tópico, usualmente el líder del Tópico más grande)*
* **S**upporter (apoyo): *cualquier persona que ayude en esta tarea para que se complete*
* **C**onsulted (consultado): *Persona que debe ser consultada para feedback o revisar la tarea, usualmente el Accountable*
* **I**nformed (informado): *Personas que deben ser avisadas del progreso de la tarea*

## Lista de items:
- [ ] Localización de 4 ejemplos de webVR (R: @lezelt) (A: @lezelt) (S: Yuliana Cecilia Viviana) (C: @lezelt)
- [ ] 1 taller online de webVR (R: viviana) (A: @lezelt) (S: @tonantzinmoya ) (C: @lezelt)
- [ ] 1 taller presencial (R: @lezelt) (A: @lezelt) (S: @yulireyji @tonantzinmoya ) (C: @lezelt)
- [ ] Contacto con comunidades que ya trabajan con WebVR (R: @yulireyji) (A: @lezelt) (S:) (C: @lezelt)
- [ ] Creación de proyecto en la plataforma "Meetup" para que al menos 30 personas se interesen y sumen al proyecto en el primer mes (R: @lezelt) (A: @lezelt) (S: @yulireyji) (C: @lezelt)

**Comment by deimidis** [comment]
Hola @LeZelt sería bueno si pueden avanzar en los roles a nivel general también. Y faltarían fechas, para saber cuándo se «teminará» el trabajo.
