### ISSUE TITLE
Generar y publicar el Código de Conducta antes del 31 de diciembre de 2016

### ISSUE THREAD

**Issue by tonantzinmoya** [mozillamexico/planes#6]
## Objetivo a alcanzar:
Generar y publicar el Código de Conducta antes del 31 de diciembre de 2016 dentro de la comunidad Mozilla México. 

## Documentos relacionados y enlaces

https://docs.google.com/document/d/1sotzvrf3HbqB4Wctv-iM_wid4tMxhgK_NiGz57PdEsM/edit?usp=sharing

##Roles

* **R**esponsable: Cecilia (@tonantzinmoya)
* **A**ccountable (quien rinde cuentas): Luis (@lars21), @tonantzinmoya
* **S**upporter (apoyo): Dani (@danysriot)
                                       Alex Fusser (@alexfuser)
                                       Liza (@elidron)
                                       Kuroneko (@KuronekoKat)
                                       Edgardo (@edgardorios)
                                       Odin (@odinm)
* **C**onsulted (consultado): Guillermo Movia (@deimidis)
* **I**nformed (informado): Miembros de la comunidad de Mozilla Mexico

## Lista de items:
- [ ] Documentar y compartir en drive el Community Playbook para que incorpore la retroalimentación de todos. (R: @tonantzinmoya, @lasr21 fecha: 24-nov)
- [ ] Recibir retroalimentación del equipo interno (R: @lasr21 @danysriot, @elidron, @KuronekoKat, @edgardorios, @odinm @deimidis -opcional- fecha: 26- nov)
- [ ] Compartir con la comunidad para recibir retroalimentación(R: @tonantzinmoya, @lasr21 30-nov)
- [ ] Publicar el código de conducta en el Wiki (R: @edgardorios, fecha: 30-nov)
- [ ] Reunión para resolver comentarios (R: @tonantzinmoya, fecha: 01-dic)

## Issues relacionados

* Es necesario incluir los mecanismos para la resolución de conflictos propuestos dicho equipo, pendiente que lo suban para actualizar el link.

**Comment by lasr21** [comment]
Community playbook traducido por Daniela y Kuro para tomar en cuenta en las guías de participación comunicaría. https://docs.google.com/document/d/1Ru4IjzYJz-SA43UZLJO4zP1KMIsCx4GGwx0fieZlNvs/edit

**Comment by lasr21** [comment]
Propuesta de código de conducta -> https://docs.google.com/document/d/1m_JLNlhwZZ4Ba2AIy3BhnZJbp6hNZ1KIgITj2Bm-tIQ/edit#

**Comment by alexfuser** [comment]
Creo que falta que agreguen mi usuario: @alexfuser :) gracias y dentro el equipo de igual forma.

**Comment by deimidis** [comment]
Hola @tonantzinmoya sería bueno agregar en el objetivo un día en el que el objetivo tenga que estar completado. Por otro lado, creo que en el objetivo falta definir qué significa «implementar», o cambiar ese verbo por otro.

Al ser el código de conducta, un documento, quizás podría ser la fecha de la publicación en la wiki, o que se incluya una forma en la cual las personas que se acercan a la comunidad pueden «firmar» su aceptación del Código

**Comment by deimidis** [comment]
Hola nuevamente, ¿han podido avanzar con este issue?

**Comment by tonantzinmoya** [comment]
@deimidis no habiamos pensado en eso de "firmar" o dar la aceptación del CoC, ¿sabes cómo lo han hecho en otras comunidades?

**Comment by lasr21** [comment]
Hola, después de varias iteraciones tenemos un código de conducta https://docs.google.com/document/d/1m_JLNlhwZZ4Ba2AIy3BhnZJbp6hNZ1KIgITj2Bm-tIQ/edit procedemos a publicarlo en el wiki y aquí para referencia

**Comment by lasr21** [comment]
Listo https://wiki.mozilla.org/C%C3%B3digo_de_conducta https://github.com/mozillamexico/codigo_conducta
