### ISSUE TITLE
Resolución de Conflictos dentro de las Comunidades de Mozilla México

### ISSUE THREAD

**Issue by ViviNava** [mozillamexico/planes#7]
# Resolución de Conflictos dentro de las Comunidades de Mozilla México

Este espacio fue requerido dentro de Community Gathering realizado los días 19 y 20 de noviembre de 2016 en la Ciudad de México con la finalidad de Documentar la resolución de conflictos dentro de las diversas comunidades de Mozilla México.
## 
**## Objetivo a alcanzar:**

Implementar las sugerencias de Soluciones brindadas por el equipo en el encuetro de Community Gathering realizado los días 19 y 20 de noviembre de 2016 en la Ciudad de México de la misma forma dentro de las que surjan durante su resolución

Documentos relacionados y enlaces

- https://public.etherpad-mozilla.org/p/mozmex16

- https://discourse.mozilla-community.org/t/definicion-individual-para-determinar-las-problematicas-y-soluciones-en-la-comunidad-de-womoz-mexico/11316

- https://discourse.mozilla-community.org/t/definiendo-el-por-que-de-womoz/11362/3

- https://discourse.mozilla-community.org/t/lineamientos-para-definir-cuando-alguien-es-activo-y-cuando-no-en-womoz/11448/15

- https://discourse.mozilla-community.org/t/mexico-community-gathering-2016-informacion-y-registro/11401

- https://discourse.mozilla-community.org/t/definiendo-el-por-que-de-womoz/11362

- https://discourse.mozilla-community.org/t/invitacion-a-la-semana-del-emprendimiento/11265/14

## Roles

* **R**esponsable: *(Obligatorio) La persona que liderará esta tarea (asigna el issue a esta persona)*
* **A**ccountable (quien rinde cuentas): *(Obligatorio) La persona que es responsable de todo el tópico, usualmente el líder del Tópico más grande)*
* **S**upporter (apoyo): *cualquier persona que ayude en esta tarea para que se complete*
* **C**onsulted (consultado): *Persona que debe ser consultada para feedback o revisar la tarea, usualmente el Accountable*
* **I**nformed (informado): *Personas que deben ser avisadas del progreso de la tarea*

## Lista de items:
- [ ] Hecho particular que debe suceder (R: @username)

### A Corto plazo
- [ ] Establecer las reglas del juego o de convivencia
- [ ] Resolución personal en privado si es que aplica
- [ ] Tener tacto al decir las cosas
- [ ] Resolución en grupo si es que aplica
- [ ] Incentivar la conducta de aprender a escuchar a las personas
- [ ] Entender que una persona que es buena en lo que hace no es intención resaltar su ego si no respaldar las actividades (que puede realizar o realiza)
- [ ] Tener tolerancia
- [ ] Hacer enterar a la comunidad de la existencia de la estructura si es que existe.
- [ ] Saber como decir las cosas

### A largo plazo

- [ ] Reunir un grupo de personas (6 aproximadamente al azar) como equipo de resolución y que en estas exista una rotativa   continua y de manera imparcial.
- [ ] Establecer una persona como castigador y juez.
- [ ] Establecer un protocolo para la resolución de conflictos
- [ ] La merintocicracia como prioridad para la toma de decisiones
- [ ] Encuentro de una persona mediadora,  una persona cuya profesión sea la Psicología
- [ ] Búsqueda de un canal de denuncia ánonima
- [ ] Procedimiento basado en código de ética 
- [ ] Hacer obligatoria la lectura de los códigos  realizar un examen para  verificar que sea aprendido.
- [ ] Si existen diferencias no tomarse nada personal realizar una guia de participación
- [ ] Tomar medidas drásticas al llegar a casos extremos
- [ ] Definir sanciones
- [ ] Aprender a trabajar en equipo
- [ ] Desarrollar métodos de capacitación
- [ ] Diseñar e implementar talleres de valores
- [ ] Implementar un código de ética
- [ ] Definir la toma de decisiones
- [ ] Definir una estructiura
- [ ] Cursos de psicologia
- [ ] Diseñar métodos de motivación
- [ ] Reuniones formales para los códigos
- [ ] Diseño de código de convivencia

## Issues relacionados

* [Referencia a issues que contienen a este o anteriores](/thelink)

**Comment by deimidis** [comment]
Hola @ViviNava habría que ve rla forma de adecuar estas ideas y procesos al formato que habíamos armado.

Por ejemplo, quizás por ahora dejaría solo un plan a corto plazo (qué es urgente hacer, o prioritario). Para otros temas podemos ir creando otros issues en otro momento.

**Comment by deimidis** [comment]
Hola @ViviNava no sé si seguís mirando github. Dime en qué puedo ayudarte para avanzar

**Comment by ViviNava** [comment]
Si por favor TTwTT tengo mucho trabajo en cierre de año

El 16 de diciembre de 2016, 13:26, Guillermo Movia <notifications@github.com

**Comment by siclemx** [comment]
@ViviNava te envíe un correito :)

**Comment by lasr21** [comment]
@ViviNava has podido revisar algo? el Código de conducta ya esta listo https://github.com/mozillamexico/planes/issues/6 hay algo en que te podamos apoayar para avanzar este punto?

@tonantzinmoya como ves?

**Comment by tonantzinmoya** [comment]
Si, podemos si quieres @vivi darle a la parte de resolución de conflictos para que veamos cómo se relaciona con el CoC, como ves?

Con cariño, Cecy

**Comment by lasr21** [comment]
Hola Mozillians, 

 Hoy en el canal de la comunidad surgio nuevamente la necesidad de avanzar en este tema, entiendo que a nadie nos gusta ser el malo y ser los que tienen que pones los castigos. 

Creo que una solución puede ser comenzar por comentar de forma anónima algunos comentarios y de ahí partir. https://public.etherpad-mozilla.org/p/mozmx_conflictos

**Comment by siclemx** [comment]
Creo que deberíamos tratar de hacerlo un poco menos uhmmmm violable, quizás algun formato publico para recabar la información, lo reportado y las medidas tomadas?

**Comment by lasr21** [comment]
@BoSicle no me explique bien, ese etherpad no es para reportar, la idea de ese etherpad es comentar sobre el procedimiento a seguir cuando se reciba una queja, como se va actuar, que grupo cuales son las medidas a tomar, etc etc

**Comment by siclemx** [comment]
Pero pues no hay trabajo en la comunidad, no se realmente porque hay peleas o quejas si realmente no se hace nada ...

**Comment by ViviNava** [comment]
sugiero que se posponga un mes, algunas personas estamos afectadas por el
sismo, a menos yo lo estoy

2017-10-02 23:11 GMT-05:00 Sicle <notifications@github.com>:

**Comment by lasr21** [comment]
Me parece correcto @ViviNava .Este tema queda en pausa hasta el 19 de Octubre.
